### PR TITLE
Add keyboard shortcut for restarting the level

### PR DESCRIPTION
**Pull request by Bocom**
Not sure if this is something anyone else wants, but I found myself reaching for the restart button a bunch and wanted to speed up the process. 😅

### CODE REVIEW

**Comment by eevee** [comment]
Hmm, this seems fairly easy to fat-finger, especially since CC2 makes use of the `Q` and `E` keys.  Adding the confirmation dialog would help, but those don't support keyboard shortcuts yet because confining keyboard focus to a modal dialog is a _nightmare_, so I'm not quite sure what to do about this.  Maybe you should have to hold it for a second or two?

**Comment by Bocom** [comment]
Oh dang, I had no idea that was the case! Hm, one solution could be to have `R` either need to be held or show the modal, and then if you hit something like `Shift+R` you bypass the confirmation? I guess then you could accidentally hit `Ctrl+R` instead, which requires extra prevention...

**Comment by TheGLander** [comment]
CC1 has `CTRL+R` for resetting the level, while CC2 has `F1` for that. Both are not that easy to accidentally press, so I would suggest using one of those keys.

**Comment by foxsouns** [comment]
> MSCC has `CTRL+R` for resetting the level, while CC2 has `F1` for that. Both are not that easy to accidentally press, so I would suggest using one of those keys.

CTRL+R refreshes the current tab for me, and F1 is difficult to press and opens the help on a chromebook.

**Comment by LeifAndersen** [comment]
Which is sad as its (imo) the best implementation of chip's challenge out there today. (Although certainly not the most 'accurate' per se, I find it the most polished, if that makes any sense.)

I wonder if @eevee would be amenable to PRs, or if forking is an option (if needed).

**Comment by foxsouns** [comment]
> Which is sad as its (imo) the best implementation of chip's challenge out there today. (Although certainly not the most 'accurate' per se, I find it the most polished, if that makes any sense.)

oh, absolutely. i would love to see progress on this.. 

> I wonder if @eevee would be amenable to PRs, or if forking is an option (if needed).

i haven't seen any responses from eevee here for quite a while.. if they're still around, im sure pr's would be fine; i've had luck contacting them in the past with their [email](mailto://github@eev.ee).

forking is _legally_ an option, of course: the whole code is MIT, and the new assets are cc-by-sa-4.0, so they would be usable, assuming credit is given and license is preserved, of course.. and there's always the option of making ANOTHER icon set, if need be.

**Comment by eevee** [comment]
I'm still here??  The repo just hasn't been updated in a while because it's 99% feature-complete, and most of the remaining stuff is awful compatibility issues.  Also because I have ADHD.

I do intend to make "hold R to restart" a thing; it just deserves some good UI to indicate that's what's happening, and I never quite got around to making that happen.

**Comment by lazerwalker** [comment]
Just to add an additional $0.02: a lot of modern Sokoban-like games allow you to press R to restart without a held input or confirmation, but simply implement "restart" as a normal action on the history stack. So if you fat-finger the restart button by mistake you can just press 'undo' and suddenly you're back to your previous in-progress game state. 

That is likely a larger refactor, and might introduce some complexity around how the timer functions, but throwing that out as an option that would resolve some interface complexity.

**Comment by eevee** [comment]
The level _state_ is completely separate from the level itself, and restarting just throws it away and creates a new one, so that might actually be very easy — just keep a stack of old level states, too.

The interaction with rewind would be kind of goofy, but maybe that's okay?  I mean, if you wanted to get back to the initial state, you can just restart again.

**Comment by TheGLander** [comment]
> Hmm, this seems fairly easy to fat-finger, especially since CC2 makes use of the `Q` and `E` keys. Adding the confirmation dialog would help, but those don't support keyboard shortcuts yet because confining keyboard focus to a modal dialog is a _nightmare_, so I'm not quite sure what to do about this. Maybe you should have to hold it for a second or two?

Oh, hey, in response to modal dialog focus: have you considered using the [native \<dialog\> element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) for dialogs? It solves the focus problem, basically completely handles itself, *and* has good browser support!

(Side note: Another shortcut I think would make sense to consider is Shift+R. It's hard to fat-finger, intuitive, and doesn't conflict with browsers)

**Comment by eevee** [comment]
I finally did this in a3b283b.  Sorry for the "delay", ho ho.

Filed #99 for undoing a restart.

Thanks for the tip about the `<dialog>` element — last time I looked (which was, I guess, when I originally wrote LL), browser support was _not_ so good.

**Pull request closed without merging**
