### PR TITLE
Implement Turn-Based Mode

### PR DESCRIPTION
**Pull request by Patashu**
I saw this was on the TODO list so I took a crack at it!

I haven't extensively tested it for gameplay bugs but it seems to work and render correctly.

### CODE REVIEW

**Comment by eevee** [comment]
whoa i definitely did not expect to be getting major pulls right off the bat!

hm, wouldn't it be simpler if this were handled in the `Player`, and it didn't advance the game at all if no keys were pressed?  seems like this goes to an awful lot of effort to make `advance_tic` do nothing, when we could not call it in the first place

**Comment by Patashu** [comment]
Yeah it's awkward that we have to put a giant interrupt in the middle of advance_tic, game logic wise. The problem is that the game loop doesn't go 'do everything in response to a player's movement, then wait for next input' like in a typical puzzle game, but deciding if the player can make a move or not and what kind of move it is happens in the middle of advance_tic. And we might be busy making an involuntary move (due to ice or force arrows) so we don't know if the player is ready for new input without running the game and finding out.

There might be a better solution though, or you could decide involuntary movement should interact with turn-based mode differently than my initial decision.

**Comment by eevee** [comment]
Ah, I see what you mean.  Well, damn; when I first wrote this down as an idea I hadn't even gotten around to smooth movement yet, so it hadn't even occurred to me that the player's movement would _end_ partway through a tic.

Maybe `_advance_tic` should be split in half, so turn-based mode can call only the first half if it has no input, and then call the second half and finish the tic once the player presses a key again?  The other cases can be readily detected by inspection — the player is idle iff they're not moving (`movement_cooldown === 0`) and not sliding (`slide_mode === null`).

Incidentally, I'm not sure `_advance_tic` should even exist; I've seen evidence that the Steam game finishes the tic normally before declaring that the game has been won or lost, so I don't actually need to abort the tic immediately.

**Comment by Patashu** [comment]
If there's an exhaustive set of conditions that determine if the player is ready for input or not, then I agree that your solution makes sense. I'll take a crack at this soon :tm:.

**Comment by Patashu** [comment]
Ok, I've made a refactor in the vein of your suggestion, and fixed a bunch of loose ends and bugs that I found in the process. I've run out of things I want to test or bug fix or feel annoyed at, so here it is again!

The game no longer knows anything about if it's being run in turn_based mode or not, which is nice.

I dropped the tic_counter modulo test, since I found a way to get misaligned by nudging a wall while on force arrows, then you just swirled on force arrows indefinitely. Now you can wait in single tic increments in turn based mode with spacebar or wall nudging! (And I suppose this is OK.)

I also made it so you could tap a key for less than a frame and still move in that direction, which is a big QoL improvement in turn based mode.

**Comment by eevee** [comment]
Checked this out locally and gave it a whirl and it is pretty radical??  Exactly what I had in mind.  I have some style nits but whatever I can fix those myself.

The one thing I'm hesitating about is an executive decision: is this "more cheating" than undo/rewind?  Is it a debugging/optimization feature, even?  But then, what's the point if I squirrel it away in a debug panel?  I'll have to figure this out before I merge.

But in the meantime, thank you!  This is a really cool and certainly different way to play.

**Comment by Patashu** [comment]
Glad you like it!

I think as soon as you have undo/rewinding then you're basically saying 'play the game however you want', since you can erase an arbitrary amount of mistakes forever, and I think ultimately people WILL play the game however they want. They're already choosing to play it in Lexy's Labyrinth instead of Tile World or whatever! If people want certified bragging rights they can livestream themselves and that's how you'd have to provide proof anyway.

**Comment by eevee** [comment]
I think you're right — and most compellingly, I realize a very determined player could just as well mash the pause button obsessively anytime they want to stop and think about their move.  (The Steam releases hide the playing field while paused, so this doesn't work there.  But Tile World doesn't, and everyone considers it plenty valid for scoring purposes.)

So I'm merging this, thank you so much!

**Comment by Patashu** [comment]
Happy to help!

**Pull request merged**
